### ISSUE TITLE
Breakage since upgrading from 1.8.1 to 1.13.1

### ISSUE THREAD

**Issue by omarandlorraine** [uuid-rs/uuid#803]
I've got some code here which used to work and now doesn't, and I'm not sure I understand exactly why.

Here is the error I'm getting:

```rust
1  error[E0283]: type annotations needed
   --> barry/src-tauri/src/site.rs:33:27
    |
 33 |         .find(|s| (s.uuid != Default::default() && s.uuid == uuid) || s.i
 p == ip)
    |                           ^^ cannot infer type
    |
    = note: multiple `impl`s satisfying `muffin::Uuid: std::cmp::PartialEq<_>`
  found in the `uuid` crate:
            - impl std::cmp::PartialEq for muffin::Uuid;
            - impl std::cmp::PartialEq<uuid::non_nil::NonNilUuid> for muffin::Uuid;

 For more information about this error, try `rustc --explain E0283`.
 error: could not compile `barry` (lib) due to 1 previous error
```

barry and muffin are (anonymised names of) my own crates, which depend on eachother. muffin exposes this crate's Uuid type with `pub use uuid::Uuid;`, and this is what breaks since the upgrade.

Does anyone know what's happened here?

**Comment by KodrAus** [comment]
@omarandlorraine You can fix this by replacing `Default::default()` with `Uuid::default()` in your comparison there.

Previously there was only one `PartialEq` implementation on `Uuid`, but now there are multiple, so the compiler can’t automatically infer what type `Default::default()` is targeting.

**Comment by omarandlorraine** [comment]
> You can fix this by replacing `Default::default()` with `Uuid::default()` in your comparison there.

That works beautifully, thanks so much for your help.
