### ISSUE TITLE
Breaking change in `v1` module in v1.2.0

### ISSUE THREAD

**Issue by jtomschroeder** [uuid-rs/uuid#635]
**What happened?**

The following compilation error occurs when upgrading from v1.1.2 to v1.2.0:

```
error[E0603]: struct `Timestamp` is private
    |
    |     use uuid::v1::{Context, Timestamp};
    |                             ^^^^^^^^^ private struct
    |
note: the struct `Timestamp` is defined here
   --> /code/.cargo/registry/src/github.com-1ecc6299db9ec823/uuid-1.2.0/src/v1.rs:6:22
    |
    | use crate::{Builder, Timestamp, Uuid};
    |                      ^^^^^^^^^
```

**What were you expecting?**

Because the new release is a minor release, I was expecting that the existing use of `uuid` at v1.x would be compatible with future minor releases.

**What's the context?**

- Target: `rustc 1.58.1 (db9d1b20b 2022-01-20)`
- Version: `uuid = { version = "1.0.0", default-features = false, features = ["v1"] }`

**Comment by KodrAus** [comment]
Thanks for pointing this out @jtomschroeder. This isn’t intentional breakage so will get a patch out.

**Comment by KodrAus** [comment]
This has been fixed up in `1.2.1`. Thanks again @jtomschroeder :bow:

**Comment by jtomschroeder** [comment]
Thank you!
